package com.cts.ecommerce.repository;

import com.cts.ecommerce.entity.Category;

import java.util.List;

/**
 * Repository abstraction for managing {@link Category} entities.
 *
 * <p>Defines the contract for persistence operations on the
 * {@code Category} table, including create, read, update, delete, and
 * existence checks. Implementations are expected to raise the
 * appropriate user-defined exceptions from
 * {@code com.cts.ecommerce.exception} when an operation fails.</p>
 */
public interface CategoryRepository {

    /**
     * Persists a new category.
     *
     * @param category the category to insert; its {@code categoryName}
     *                 is read and a new identifier is generated by the database
     * @return the number of rows affected (typically {@code 1} on success)
     */
    int save(Category category);

    /**
     * Updates an existing category.
     *
     * @param category the category carrying the new values; its
     *                 {@code categoryId} identifies the row to update
     * @return the number of rows affected ({@code 1} if a matching row
     *         was found, {@code 0} otherwise)
     */
    int update(Category category);

    /**
     * Deletes the category with the given identifier.
     *
     * @param categoryId the identifier of the category to delete
     * @return the number of rows affected ({@code 1} if a matching row
     *         was found, {@code 0} otherwise)
     */
    int deleteById(int categoryId);

    /**
     * Retrieves a single category by its identifier.
     *
     * @param categoryId the identifier of the category to look up
     * @return the matching {@link Category}
     */
    Category findById(int categoryId);

    /**
     * Retrieves every category in the system, ordered by id.
     *
     * @return a list of all categories; never {@code null}, possibly empty
     */
    List<Category> findAll();

    /**
     * Checks whether a category with the given identifier exists.
     *
     * @param categoryId the identifier to check
     * @return {@code true} if a category with that id exists,
     *         {@code false} otherwise
     */
    boolean existsById(int categoryId);
}

